### ISSUE TITLE
/subscribe status message not updating in big server

### ISSUE THREAD

**Issue by jgaribsin** [jgaribsin/hellcom#1]
https://discord.com/channels/1046247991582916618/1218248649449013249

relevant info:
- function is not broken for other servers
- tried increasing the interval (10mins to 60mins)
- tried unsubbing and redoing the command, made the message fine but fails to update
- roughly 8k users
- is not an announcement channel (works in other non-announcement channels)
- self-perms check passed just fine
- 
![image](https://github.com/jgaribsin/helldivers2-bot/assets/16392336/266d7241-1cf1-49fe-998a-33eb95b1fd92)

**Comment by Krojack** [comment]
I just noticed this on my small private server with ~4 people and ~4 other bots total. 

![image](https://github.com/jgaribsin/hellcom/assets/908461/dcb2da9c-1a34-45ec-8994-9e034ff3b5df)

**Comment by jgaribsin** [comment]
> I just noticed this on my small private server with ~4 people and ~4 other bots total.
> 
> ![image](https://private-user-images.githubusercontent.com/908461/316116477-dcb2da9c-1a34-45ec-8994-9e034ff3b5df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExNTA2NjUsIm5iZiI6MTcxMTE1MDM2NSwicGF0aCI6Ii85MDg0NjEvMzE2MTE2NDc3LWRjYjJkYTljLTFhMzQtNDVlYy04OTk0LTllMDM0ZmYzYjVkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMlQyMzMyNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNTJmNmJkOWE0MDkwODIyMGYyYmQ1Zjg5YmRhZTZiMGIzMjQzZmU1NTFjOTUwNWJhMjg4YTI4NjBjM2VmOGJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._7RWY1-ScOlomnXRA5vS5l31-uqXmPkdUlkqiomz6EY)

Yep, got wind of that through some other reports and I managed to recreate it myself in a server with only myself and two bots. I'm working on figuring out the issue and trying various things in hopes of a fix.

**Comment by Krojack** [comment]
Mine as started updating every 15 mins now.

Might I also add a suggestion... Add a "footer" in the embed for both the Automatons and Teminids that has the last updated time stamp. I do it for my Palworld server.. Looks like this

![image](https://github.com/jgaribsin/hellcom/assets/908461/3e0208cb-5a02-4504-904d-b494e4898d06)

JSon Code:
`      "footer": {
        "text": "Last Update"
      },
      "timestamp": "2024-03-23T00:47:17.000Z"
`

**Comment by jgaribsin** [comment]
Update issue is fixed as of b4a3c91 with subsequent patch for efficiency. Thanks for confirming =)


> Mine as started updating every 15 mins now.
> 
> Might I also add a suggestion... Add a "footer" in the embed for both the Automatons and Teminids that has the last updated time stamp. I do it for my Palworld server.. Looks like this
> 
> ![image](https://private-user-images.githubusercontent.com/908461/316204673-3e0208cb-5a02-4504-904d-b494e4898d06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExNTUzNDQsIm5iZiI6MTcxMTE1NTA0NCwicGF0aCI6Ii85MDg0NjEvMzE2MjA0NjczLTNlMDIwOGNiLTVhMDItNDUwNC05MDRkLWI0OTRlNDg5OGQwNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyM1QwMDUwNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZDMyYWYzNmNiZmZmOWY0NWViMzA5ZDY3YmNjYmNjODlkM2I4NTc1ODA4YTVhNzJmMmRhNGRjYWFlOGZjMDQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9IFYXBXv0uHYb5dmTprqe3HK8lK5LCJt-n0vY4yS2qk)
> 
> JSon Code: ` "footer": { "text": "Last Update" }, "timestamp": "2024-03-23T00:47:17.000Z"`

I figured the update notes in the final embed would be enough since all embeds are part of the same message. This seems like code duplication unless I'm missing something? 

I'm closing this since this is a report about broken message updates, but can make another issue with a suggestion label if you'd like!
