### ISSUE TITLE
"Time Left" on campaign embed for defend planets broken.

### ISSUE THREAD

**Issue by EnderInvader** [jgaribsin/hellcom#4]
expireTime is still 'Helldivers Time' and not UTC time but is being subtracted by UTC time.

![image](https://github.com/jgaribsin/hellcom/assets/20405891/f4c955a0-0108-4d98-a18b-9363f5f5f99e)

https://github.com/jgaribsin/hellcom/blob/61a23454a85558534ff7ca6c785bd6c2d1c401c5/src/handlers/embed.ts#L407

-----

Could be changed to reflect timecodes used in the dispatch log embed:

![image](https://github.com/jgaribsin/hellcom/assets/20405891/59f808e5-03d2-4b59-811b-0e56c32b6ee8)

https://github.com/jgaribsin/hellcom/blob/61a23454a85558534ff7ca6c785bd6c2d1c401c5/src/api-wrapper/api.ts#L155
https://github.com/jgaribsin/hellcom/blob/61a23454a85558534ff7ca6c785bd6c2d1c401c5/src/commands/dispatches.ts#L38-L40

**Comment by jgaribsin** [comment]
fixed with 861dba6a49ac68b8be16c3a123656133f700b761
